env:
  version: 1.20.2 #artifact version
  username: ${GITHUB_ACTOR}

name: nginx

on:
  push:
    paths-ignore:
      - 'nginx/**'
      - '**/README.md'
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: imranismail/setup-kustomize@v1
      - 
        name: Kustomize
        run: |
          cd nginx/env/stage
          kustomize edit set nameprefix ${{ env.username.uppercase }}-
          kustomize edit set image library/nginx:${{ env.version }}
          git config --global user.name "Commit Bot"
          git config --global user.email "no-reply@akuity.io"
          git add .
          git commit -m "Set library/nginx image tag to ${{ env.version }}"
          git push
